INFO     root:genKeyword.py:172 Closing browser
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221F3FD4E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/fbb0da81-c760-4de5-88e7-705f9d2ec076/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221F3FC9190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/fbb0da81-c760-4de5-88e7-705f9d2ec076/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221F3FBC850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/fbb0da81-c760-4de5-88e7-705f9d2ec076/screenshot